import covers from './coversData';

const booksData = [
    //Fantasy
    {
        title: 'Harry Potter Set (1-7)',
        author: 'J.K. Rowling',
        price: '$40.87',
        genre: "Fantasy",
        img: covers.harryPotter,
    },
    {
        title: 'The Hobbit',
        author: 'J. R. R. Tolkien',
        price: '$20',
        genre: "Fantasy",
        img: covers.hobbit,
    },
    {
        title: 'The Last Unicorn',
        author: 'Peter S. Beagle',
        price: '$10.07',
        genre: "Fantasy",
        img: covers.unicorn,
    },
    {
        title: 'Ancient Sorceries and Other Weird Stories',
        author: 'Algernon Blackwood',
        price: '$14.72',
        genre: "Fantasy",
        img: covers.weird,
    },
    {
        title: 'A Journal of the Plague Year',
        author: 'Daniel Defoe',
        price: '$10.22',
        genre: "Fantasy",
        img: covers.plague,
    },
    {
        title: 'The Hero and the Crown',
        author: 'Robin McKinley',
        price: '$8.87',
        genre: "Fantasy",
        img: covers.heroCrown,
    },
    {
        title: 'The Lightning Thief',
        author: 'Rick Riordan',
        price: '$8.00',
        genre: "Fantasy",
        img: covers.lightThief,
    },
    {
        title: 'Six of Crows',
        author: 'Leigh Bardugo',
        price: '$12.00',
        genre: "Fantasy",
        img: covers.sixCrows,
    },
    //Romance
    {
        title: 'Mountains (Books 1-5)',
        author: 'P.D. Singer',
        price: '$25.87',
        genre: "Romance",
        img: covers.mountainsBundle,
    },
    {
        title: 'The Highlander’s Pirate Lass 2',
        author: 'Heather McCollum',
        price: '$25.87',
        genre: "Romance",
        img: covers.highlanderPirate,
    },
    {
        title: 'The Fault in Our Stars',
        author: 'John Green',
        price: '$4.99',
        genre: "Romance",
        img: covers.faultStars,
    },
    {
        title: 'Red, White & Royal Blue',
        author: 'Casey McQuiston',
        price: '$6.99',
        genre: "Romance",
        img: covers.redwhiteloyal,
    },
    {
        title: 'Twilight (The Twilight Saga #1)',
        author: 'Stephenie Meyer',
        price: '$8.01',
        genre: "Romance",
        img: covers.twilight,
    },
    //Horror
    {
        title: 'The Shining',
        author: 'Stephen King',
        price: '$10.00',
        genre: "Horror",
        img: covers.shining,
    },
    {
        title: 'It',
        author: 'Stephen King',
        price: '$12.00',
        genre: "Horror",
        img: covers.it,
    },
    {
        title: 'Dracula',
        author: 'Bram Stoker',
        price: '$15.00',
        genre: "Horror",
        img: covers.dracula,
    },
    {
        title: 'The Tommyknockers',
        author: 'Stephen King',
        price: '$19.99',
        genre: "Horror",
        img: covers.tommy,
    },
    //History
    {
        title: 'Sapiens: A Brief History of Humankind',
        author: 'Yuval Noah Harari',
        price: '$8.99',
        genre: "History",
        img: covers.sapiens,
    },
    {
        title: 'Guns, Germs, and Steel',
        author: ' Jared Diamond',
        price: '$4.99',
        genre: "History",
        img: covers.guns,
    },
    {
        title: '1776',
        author: 'David McCullough',
        price: '$5.55',
        genre: "History",
        img: covers.a1776,
    },
    {
        title: 'The Rise and Fall of the Third Reich',
        author: 'William L. Shirer',
        price: '$20.99',
        genre: "History",
        img: covers.riseFall,
    },
    //Languages
    {
        title: 'Fluent Forever',
        author: 'Gabriel Wyner',
        price: '$2.99',
        genre: "Languages",
        img: covers.fluentForever,
    },
    {
        title: 'The Mother Tongue: English and How It Got That Way',
        author: 'Bill Bryson',
        price: '$4.92',
        genre: "Languages",
        img: covers.motherTongue,
    },
    {
        title: 'The Language Instinct',
        author: 'Steven Pinker',
        price: '$12.00',
        genre: "Languages",
        img: covers.languageInstinct,
    },
    {
        title: 'Polyglot: How I Learn Languages',
        author: 'Kató Lomb',
        price: '$13.99',
        genre: "Languages",
        img: covers.polyglot,
    },
    {
        title: "Lingo: A Language Spotter's Guide to Europe",
        author: 'Gaston Dorren',
        price: '$12.99',
        genre: "Languages",
        img: covers.lingo,
    },
    {
        title: 'Eats, Shoots & Leaves',
        author: 'Lynne Truss',
        price: '$15.00',
        genre: "Languages",
        img: covers.eatShoots,
    },
    //Manga
    {
        title: 'Death Note, Vol. 1: Boredom',
        author: 'Tsugumi Ohba',
        price: '$5.00',
        genre: "Manga",
        img: covers.deathNote,
    },
    {
        title: 'Attack on Titan, Vol. 1',
        author: 'Hajime Isayama',
        price: '$7.00',
        genre: "Manga",
        img: covers.titan,
    },
    {
        title: 'Fullmetal Alchemist, Vol. 1',
        author: 'Hiromu Arakawa',
        price: '$4.00',
        genre: "Manga",
        img: covers.fma,
    },
    {
        title: 'Black Butler, Vol. 1',
        author: 'Yana Toboso',
        price: '$5.00',
        genre: "Manga",
        img: covers.butler,
    },
    {
        title: 'Vampire Knight, Vol. 1',
        author: 'Matsuri Hino',
        price: '$5.00',
        genre: "Manga",
        img: covers.vampireNight,
    },
    {
        title: 'Inuyasha, Vol. 1',
        author: 'Rumiko Takahashi',
        price: '$3.00',
        genre: "Manga",
        img: covers.inuyasha,
    },
    {
        title: 'Tsubasa: RESERVoir CHRoNiCLE, Vol. 1',
        author: 'CLAMP',
        price: '$5.00',
        genre: "Manga",
        img: covers.tsubasa,
    },
    {
        title: 'Fruits Basket, Vol. 6',
        author: 'Natsuki Takaya',
        price: '$5.00',
        genre: "Manga",
        img: covers.fruits6,
    },
    {
        title: 'Attack on Titan, Vol. 2',
        author: 'Hajime Isayama',
        price: '$7.00',
        genre: "Manga",
        img: covers.titan2,
    },
    //Mystery
    {
        title: 'And Then There Were None',
        author: 'Agatha Christie',
        price: '$15.00',
        genre: "Mystery",
        img: covers.andThen,
    },
    {
        title: 'The Girl with the Dragon Tattoo',
        author: 'Stieg Larsson',
        price: '$12.20',
        genre: "Mystery",
        img: covers.girlDragon,
    },
    {
        title: 'The Da Vinci Code',
        author: 'Dan Brown',
        price: '$18.00',
        genre: "Mystery",
        img: covers.daVinci,
    },
    //Cooking Books
    {
        title: 'Joy of Cooking',
        author: 'Irma S. Rombauer',
        price: '$11.00',
        genre: "Cooking Books",
        img: covers.joyCooking,
    },
    {
        title: 'Veganomicon: The Ultimate Vegan Cookbook',
        author: 'Isa Chandra Moskowitz',
        price: '$13.00',
        genre: "Cooking Books",
        img: covers.veganomicon,
    },
    {
        title: 'How to Cook Everything',
        author: 'Mark Bittman',
        price: '$14.00',
        genre: "Cooking Books",
        img: covers.cookEverything,
    },
    {
        title: 'The Smitten Kitchen Cookbook',
        author: 'Deb Perelman',
        price: '$16.00',
        genre: "Cooking Books",
        img: covers.smitten,
    },
]

export default booksData;

